eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/

server:
 port: 8766

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
spring:
 data:
  elasticsearch:
   cluster-name: my-application
   cluster-nodes: 192.168.1.6:9300
   client:
    reactive:
     endpoints: http://192.168.1.6:9200
   repositories:
    enabled: true
