eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/

server:
 port: 8766

spring:
 application:
  name: connect_to_es

 data:
   elasticsearch:
     client:
       reactive:
         endpoints: http://localhost:9200
     repositories:
       enabled: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
